### ISSUE TITLE
Mega Menu's Collapse is collapsing on desktop too with tailwindcss ver 3.2.4

### ISSUE THREAD

**Issue by anjanesh** [mdbootstrap/TW-Elements#1328]
Expected behavior : `collapse` class should hide on desktop

Actual behavior : `collapse` class is collapsing on desktop

Resources (screenshots, code snippets etc.) https://tailwind-elements.com/docs/standard/navigation/mega-menu/ doesn't work with 3.2.4 - I had to revert to version 3.0.24 to get the Mega Menu to work

```
<div class="navbar-collapse collapse grow items-center min-w-full" id="navbarSupportedContentX"> 
```

**Comment by smolenski-mikolaj** [comment]
We've just released the new v1.0.0-beta1 version synced with Tailwind 3.2.4 so after update the issue should be fixed.

**Comment by anjanesh** [comment]
Thanks - How do I get the beta from the CDN ? https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js or do I wait till 1 is final ?

**Comment by smolenski-mikolaj** [comment]
You can pick any version on cdn by using `@` sign like this:
`https://cdn.jsdelivr.net/npm/tw-elements@v1.0.0-alpha13/dist/js/index.min.js`

Path without `@` sign is always the latest, so the one you shared above is in fact `v1.0.0-beta1`.

**Comment by anjanesh** [comment]
The entire navmenu disappeared when I switched to 3.2.4 - I didn't have time to debug so switched back to 3.0.24

**Comment by malle-pietje** [comment]
> The entire navmenu disappeared when I switched to 3.2.4 - I didn't have time to debug so switched back to 3.0.24

Same here. Strange thing is that the navbar using `collapse` is still showing up with Chromium browsers but not with (Mobile) Safari and Firefox. Non-functional though.

This is using Tailwind 3.2.7 and Tailwind-elements 1.0.0-beta1.

**Comment by Trochonovitz** [comment]
With the beta1 we changed custom classes and Bootstrap classes in favor of these from Tailwind. So any navbar or mega menu do not have `collapse` class. Updated example are available in documentation.
